import { Text } from "react-native";
export default function TextTest(): JSX.Element {
  return (
    <>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
      <Text>Teste</Text>
    </>
  );
}
