export type voidish = null | undefined;
export type looseNum = string | number;
export type voidishStr = string | voidish;
export type voidishLooseNum = looseNum | voidish;
export type validImgExntesions =
  | "jpeg"
  | "jpg"
  | "png"
  | "gif"
  | "svg"
  | "webp"
  | "bmp"
  | "ico"
  | "tiff"
  | "heif"
  | "avif"
  | "pdf"
  | "invalidExtension";
export type numSets = "whole" | "natural" | "integer" | "rational" | "real";
export type socialMedia =
  | "discord"
  | "instagram"
  | "facebook"
  | "twitter"
  | "youtube"
  | "twitch";
export type mainFooterCases =
  | "authors"
  | "contact"
  | "cookies"
  | "team"
  | "terms";
export type pagesCases = "home" | "new-user" | "active-user" | "classes" | "/";
export type FourNumCases = 0 | 1 | 2 | 3;
export type urlCases =
  | "Algebra"
  | "Statistics"
  | "Probability"
  | "Combinatorics"
  | "Trigonometry"
  | "Geometry"
  | "";
export type AlgebraFormulaNamesReg =
  | "Linear Formula"
  | "Discriminant"
  | "Number of Roots"
  | "Quadratic Formula"
  | "Cubic Formula"
  | "Difference of Squares"
  | "Binomial Theorem"
  | "Least Common Multiple"
  | "Greatest Common Divisor"
  | "Common Difference of Arithmetic Series"
  | "Nth term of Arithmetic Series"
  | "Sum of Arithmetic Series"
  | "Reason for Geometric Series"
  | "Nth Term of Geometric Series"
  | "Sum of Geometric Series";
export type algebraFormulaNames =
  | "linearFormula"
  | "discriminant"
  | "numberOfRoots"
  | "quadraticFormula"
  | "cubicFormula"
  | "differenceOfSquares"
  | "binominalTheorem"
  | "leastCommonMultiple"
  | "greatestCommonDivisor"
  | "commonDifferenceOfArithmeticSeries"
  | "nthTermOfArithmeticSeries"
  | "sumOfArithmeticSeries"
  | "reasonForGeometricSeries"
  | "nthTermOfGeometricSeries"
  | "sumOfGeometricSeries";
export type CombinatoricsFormulasNamesReg =
  | "Permutation"
  | "MultisetPermutation";
export type combinatoricsFormulaNames = "permutation" | "multisetPermutation";
export type CombinationsTypesReg =
  | "Permutation Without Repetition"
  | "Circular Permutation"
  | "Distinct Permutation Without Repetition"
  | "Distinct Permutation with Repetition"
  | "Combination Without Repetition"
  | "Combination with Repetition";
export type combinationsTypes =
  | "permutationWithoutRepetition"
  | "circularPermutation"
  | "distinctPermutationWithoutRepetition"
  | "distinctPermutationWithRepetition"
  | "combinationWithoutRepetition"
  | "combinationWithRepetition";
export type StatisticsFormulaNamesReg =
  | "Arithmetic Mean"
  | "Harmonic Mean"
  | "Geometric Mean"
  | "Median"
  | "Mode"
  | "Arithmetic Variance"
  | "Geometric Variance"
  | "Covariance"
  | "Arithmetic Standard Deviation"
  | "Geometric Standard Deviation"
  | "Coefficient of Correlation"
  | "First Quartil"
  | "First Quartil Index"
  | "Second Quartil"
  | "Second Quartil Index"
  | "Third Quartil"
  | "Third Quartil Index"
  | "Interval between Quartils"
  | "Upper Whisker"
  | "Lower Whisker"
  | "Lower Outliers"
  | "Upper Outliers"
  | "Pearson's Assymetry Index"
  | "Person's Correlation Test"
  | "Pearson's Correlation Index"
  | "Pearsons's Coefficient of Contingency"
  | "Curtosis"
  | "Z-score"
  | "Regression Line"
  | "Chi-squared Frequency"
  | "Degree of Freedom for Chi-squared Test for Fitness"
  | "Degree of Freedom for Chi-squared Test"
  | "Degree of Freedom for Chi-squared Test for Independence"
  | "Z-score";
export type statisticsFormulaNames =
  | "arithmeticMean"
  | "harmonicMean"
  | "geometricMean"
  | "median"
  | "mode"
  | "arithmeticVariance"
  | "geometricVariance"
  | "covariance"
  | "arithmeticStandardDeviation"
  | "geometricStandardDeviation"
  | "coefficientOfCorrelation"
  | "firstQuartil"
  | "firstQuartilIndex"
  | "secondQuartil"
  | "secondQuartilIndex"
  | "thirdQuartil"
  | "thirdQuartilIndex"
  | "intervalBetweenQuartils"
  | "upperWhisker"
  | "lowerWhisker"
  | "lowerOutliers"
  | "upperOutliers"
  | "pearsonsAssymetryIndex"
  | "pearsonsCorrelationTest"
  | "pearsonsCorrelationIndex"
  | "pearsonsCoefficienteOfContingency"
  | "curtosis"
  | "zScore"
  | "regressionLine"
  | "chi__squaredFrequency"
  | "degreeOfFreedomForChi__squaredFrequencyForFitness"
  | "degreeOfFreedomForChi__squaredFrequencyForIndependence"
  | "z__score";
export type ProbabilityFormulaNamesReg =
  | "Simpe Probability"
  | "Probability in a List"
  | "Probability of Intersection of Independent Events"
  | "Probability of Intersection of Dependent Events"
  | "Probability of Union of Independent Events"
  | "Probability of Union of Dependent Events"
  | "Probability of Union"
  | "Conditional Probability"
  | "Bayes Theorem"
  | "Binomial Distribution for Discrete Variables"
  | "Expected Value"
  | "Binomial Distribution for Continuous Variables";
export type probabilityFormulaNames =
  | "simpeProbability"
  | "probabilityInAList"
  | "probabilityOfIntersectionOfIndependentEvents"
  | "probabilityOfIntersectionOfDependentEvents"
  | "probabilityOfUnionOfIndependentEvents"
  | "probabilityOfUnionOfDependentEvents"
  | "conditionalProbability"
  | "bayesTheorem"
  | "binomialDistributionForDiscreteVariables"
  | "expectedValue"
  | "binomialDistributionForContinuousVariables";
export type TrigonometryFormulaNamesReg =
  | "Sine"
  | "Cosine"
  | "Tangent"
  | "Secant"
  | "Cosecant"
  | "Cotangent"
  | "Sine Angle"
  | "Cosine Angle"
  | "Tangent Angle"
  | "Hyperbolic Sine"
  | "Hyperbolic Cosine"
  | "Hyperbolic Tangent"
  | "Angle of Hyperbolic Sine"
  | "Angle of Hyperbolic Cosine"
  | "Angle of Hyperbolic Tangent"
  | "Point of Tangent Angle"
  | "Hypotenuse"
  | "Triangle Legs"
  | "Sine As Cofunction"
  | "Cosine As Cofunction"
  | "Tangent As Cofunction"
  | "Secant As Cofunction"
  | "Cotangent As Cofunction"
  | "Sine with Pythagorean Identity"
  | "Cosine with Pythagorean Identity"
  | "Tangent with Pythagorean Identity"
  | "Secant with Pythagorean Identity"
  | "Cotangent with Pythagorean Identity"
  | "Cosecant with Pythagorean Identity"
  | "Law of Sines"
  | "Law of Cosines"
  | "Halved Angled Sine"
  | "Halved Angled Cosine"
  | "Halved Angle Tangent"
  | "Double Angled Sine"
  | "Double Angled Cosine"
  | "Double Angled Tangent"
  | "Triple Angled Sine"
  | "Triple Angled Cosine"
  | "Triple Angled Tangent"
  | "Sine for United Angles"
  | "Sine for Added Angles"
  | "Sine for Subtracted Angles"
  | "Cosine for United Angles"
  | "Cosine for Added Angles"
  | "Cosine for Subtracted Angles"
  | "Tangent for United Angles"
  | "Tangent for Added Angles"
  | "Tangent for Subtracted Angles";
export type trigonometryFormulaNames =
  | "sine"
  | "cosine"
  | "tangent"
  | "secant"
  | "cosecant"
  | "contangent"
  | "sineAngle"
  | "cosineAngle"
  | "tangentAngle"
  | "hyperbolicSine"
  | "hyperbolicCosine"
  | "hyperbolicTangent"
  | "angleOfHyperbolicSine"
  | "angleOfHyperbolicCosine"
  | "angleOfHyperbolicTangent"
  | "pointOfTangentAngle"
  | "hypotenuse"
  | "triangleLegs"
  | "sineAsCofunction"
  | "cosineAsCofunction"
  | "tangentAsCofunction"
  | "secantAsCofunction"
  | "secantAsCofunction"
  | "cotangentAsCofunction"
  | "sineWithPythagoreanIdentity"
  | "cosineWithPythagoreanIdentity"
  | "tangentWithPythagoreanIdentity"
  | "secantWithPythagoreanIdentity"
  | "cotangentWithPythagoreanIdentity"
  | "cosecantWithPythagoreanIdentity"
  | "lawOfSines"
  | "lawOfCosines"
  | "halvedAngledSine"
  | "halvedAngledCosine"
  | "halvedAngleTangent"
  | "doubleAngledSine"
  | "doubleAngledCosine"
  | "doubleAngledTangent"
  | "tripleAngledSine"
  | "tripleAngledCosine"
  | "tripleAngledTangent"
  | "sineForUnitedAngles"
  | "sineForAddedAngles"
  | "sineForSubtractedAngles"
  | "cosineForUnitedAngles"
  | "cosineForAddedAngles"
  | "cosineForSubtractedAngles"
  | "tangentForUnitedAngles"
  | "tangentForAddedAngles"
  | "tangentForSubtractedAngles";
export type GeometryFormulaNamesReg =
  | "Triangle Area"
  | "Triangle Perimeter"
  | "Rectangle Area"
  | "Rectangle Perimeter"
  | "Trapezoid Area"
  | "Trapezoid Perimeter"
  | "Parallelogram Area"
  | "Parallelogram Perimeter"
  | "Ellipsis Area"
  | "Ellipsis Perimeter"
  | "Circle Area"
  | "Circle Perimeter"
  | "Circle Ring"
  | "Circle Sector Area"
  | "Circle Sector Length"
  | "Triangular Pyramid Area"
  | "Triangular Pyramid Volume"
  | "Square Pyramid Area"
  | "Square Pyramid Volume"
  | "Cone Area"
  | "Cone Volume"
  | "Cone of Frustum Area"
  | "Cone of Frustum Volume"
  | "Cuboid Area"
  | "Cuboid Volume"
  | "Cube Area"
  | "Cube Volume"
  | "Prism Area"
  | "Prism Volume"
  | "Sphere Area"
  | "Sphere Volume"
  | "Torus Area"
  | "Torus Volume"
  | "Torus Major Radius";
export type geometryFormulaNames =
  | "triangleArea"
  | "trianglePerimeter"
  | "rectangleArea"
  | "rectanglePerimeter"
  | "trapezoidArea"
  | "trapezoidPerimeter"
  | "parallelogramArea"
  | "parallelogramPerimeter"
  | "ellipsisArea"
  | "ellipsisPerimeter"
  | "circleArea"
  | "circlePerimeter"
  | "circleRing"
  | "circleSectorArea"
  | "circleSectorLength"
  | "triangularPyramidArea"
  | "triangularPyramidVolume"
  | "squarePyramidArea"
  | "squarePyramidVolume"
  | "coneArea"
  | "coneVolume"
  | "coneOfFrustumArea"
  | "coneOfFrustumVolume"
  | "cuboidArea"
  | "cuboidVolume"
  | "cubeArea"
  | "cubeVolume"
  | "prismArea"
  | "prismVolume"
  | "sphereArea"
  | "sphereVolume"
  | "torusArea"
  | "torusVolume"
  | "torusMajorRadius";
